# Generated by Django 3.2.4 on 2021-06-27 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('preparo', models.TextField()),
                ('porcao', models.IntegerField()),
                ('tempoPreparo', models.TimeField()),
                ('publicacao', models.DateTimeField(auto_now=True)),
                ('infoAdicional', models.TextField()),
            ],
        ),
    ]
