# Generated by Django 3.2.4 on 2021-06-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogReceita', '0002_alter_receita_tempopreparo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='porcao',
            field=models.PositiveIntegerField(),
        ),
    ]
