# Generated by Django 3.2.4 on 2021-06-27 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogReceita', '0003_alter_receita_porcao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receita',
            options={'verbose_name_plural': 'Receitas'},
        ),
        migrations.AddField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='infoAdicional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
