# Generated by Django 3.2.4 on 2021-06-27 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogReceita', '0004_auto_20210627_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
