# Generated by Django 3.2.4 on 2021-06-27 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogReceita', '0005_alter_receita_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='imagem',
        ),
    ]
